# Generated by Django 3.2.3 on 2021-05-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('AS', 'Asus'), ('L', 'Lenovo'), ('M', 'Macbook'), ('AC', 'Acer'), ('D', 'Dell'), ('H', 'HP'), ('MSI', 'MSI'), ('LG', 'LG')], max_length=3),
        ),
    ]
