# Generated by Django 3.2.3 on 2021-05-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('AS', 'Asus'), ('L', 'Lenovo'), ('M', 'Macbook'), ('AC', 'Acer'), ('D', 'Dell'), ('H', 'HP'), ('MSI', 'MSI'), ('LG', 'LG'), ('SN', 'Sony'), ('AP', 'Apple'), ('SS', 'Samsung'), ('LGT', 'Logitech'), ('TCN', 'Tucano'), ('TOM', 'Tomtoc'), ('WW', 'Wiwu'), ('MZ', 'Mozard')], max_length=3),
        ),
    ]
