# Generated by Django 3.2.3 on 2021-05-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('ASUS', 'Asus'), ('LENOVO', 'Lenovo'), ('MACBOOK', 'Macbook'), ('ACER', 'Acer'), ('DELL', 'Dell'), ('HP', 'HP'), ('MSI', 'MSI'), ('LG', 'LG'), ('SN', 'Sony'), ('AP', 'Apple'), ('SS', 'Samsung'), ('LGT', 'Logitech'), ('TCN', 'Tucano'), ('TOM', 'Tomtoc'), ('WW', 'Wiwu'), ('MZ', 'Mozard'), ('PTO', 'Patriot'), ('KL', 'Kalevv'), ('TEA', 'Team group'), ('GG', 'Gigabyte'), ('KST', 'Kingston')], max_length=9),
        ),
    ]
