# Generated by Django 3.2.3 on 2021-06-01 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='city',
            new_name='district',
        ),
    ]
