# Generated by Django 3.2.4 on 2021-06-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=84338320932, max_length=10),
            preserve_default=False,
        ),
    ]
